// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOmBxoiEE4C6mhGKvm1JaL8UjSXmufOsE',
    appId: '1:1022795613924:web:3598cf351b5a11098a4ef1',
    messagingSenderId: '1022795613924',
    projectId: 'g1-app-6c3c4',
    authDomain: 'g1-app-6c3c4.firebaseapp.com',
    storageBucket: 'g1-app-6c3c4.appspot.com',
    measurementId: 'G-R3BMD392FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACz4dFboP0J8SmMKXFkseMzRqFfvALUhI',
    appId: '1:1022795613924:android:7dd11b0500f078a68a4ef1',
    messagingSenderId: '1022795613924',
    projectId: 'g1-app-6c3c4',
    storageBucket: 'g1-app-6c3c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHITHrUWozorIuYLytCXY7ApKVF0TJpBI',
    appId: '1:1022795613924:ios:e1e71b8dbb75745e8a4ef1',
    messagingSenderId: '1022795613924',
    projectId: 'g1-app-6c3c4',
    storageBucket: 'g1-app-6c3c4.appspot.com',
    iosClientId: '1022795613924-pk8u3gl3vccj0nn80r82l50ti92uu45e.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHITHrUWozorIuYLytCXY7ApKVF0TJpBI',
    appId: '1:1022795613924:ios:e1e71b8dbb75745e8a4ef1',
    messagingSenderId: '1022795613924',
    projectId: 'g1-app-6c3c4',
    storageBucket: 'g1-app-6c3c4.appspot.com',
    iosClientId: '1022795613924-pk8u3gl3vccj0nn80r82l50ti92uu45e.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOmBxoiEE4C6mhGKvm1JaL8UjSXmufOsE',
    appId: '1:1022795613924:web:df781b401afa9c1d8a4ef1',
    messagingSenderId: '1022795613924',
    projectId: 'g1-app-6c3c4',
    authDomain: 'g1-app-6c3c4.firebaseapp.com',
    storageBucket: 'g1-app-6c3c4.appspot.com',
    measurementId: 'G-G61VKVJ3YD',
  );
}
